version: "3.7"

services:
  client.web:
    build: ./frontend/client.web
    image: kiuru/client.web:latest
    ports:
      - "8000:80"

  service.auth:
    build: ./backend/service.auth
    image: kiuru/service.auth:latest
    ports:
      - "8001:8081"
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      CRDB_HOST: db.cockroach
      CRDB_PORT: 26257
      CRDB_USER: kiuru_service
      CRDB_DBNAME: kiuru
      REDIS_HOST: db.redis
      REDIS_PORT: 6379
      JWT_SECRET: my-secret-key
      JWT_ISSUER: kiuru.service.auth
      JWT_TTL: 15m

  service.user:
    build: ./backend/service.user
    image: kiuru/service.user:latest
    ports:
      - "8002:8081"
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      CRDB_HOST: db.cockroach
      CRDB_PORT: 26257
      CRDB_USER: kiuru_service
      CRDB_DBNAME: kiuru
      REDIS_HOST: db.redis
      REDIS_PORT: 6379
      JWT_SECRET: my-secret-key

  db.cockroach:
    image: cockroachdb/cockroach:v19.1.4
    command: start --insecure
    ports:
      - "26257:26257"
      - "9000:8080"

  db.cockroach.init:
    image: cockroachdb/cockroach:v19.1.4
    entrypoint: /cockroach/init/init-db
    command: db.cockroach:26257
    volumes:
      - ./databases/cockroach/init:/cockroach/init

  db.redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
