version: "3.7"

services:
  client.web:
    build: ./frontend/client.web
    image: kru-travel/client.web:latest
    ports:
      - "8000:80"

  service.auth:
    build:
      context: ./backend/service.auth
      dockerfile: dev.Dockerfile
    image: kru-travel/service.auth:latest
    environment:
      CRDB_HOST: db.cockroach
      CRDB_PORT: 26257
      REDIS_HOST: db.redis
      CRDB_PORT: 6379
    ports:
      - "8001:8081"

  service.user:
    build:
      context: ./backend/service.user
      dockerfile: dev.Dockerfile
    image: kru-travel/service.user:latest
    environment:
      CRDB_HOST: db.cockroach
      CRDB_PORT: 26257
    ports:
      - "8002:8081"

  db.cockroach:
    image: cockroachdb/cockroach:v19.1.4
    command: start --insecure
    ports:
      - "26257:26257"
      - "9000:8080"
    # volumes:
    #   - ./databases/cockroach/cockroach-data/roach-one:/cockroach/cockroach-data

  db.cockroach.sidecar:
    image: cockroachdb/cockroach:v19.1.4
    entrypoint: /cockroach/sidecar/init-db
    command: db.cockroach:26257
    volumes:
      - ./databases/cockroach/sidecar:/cockroach/sidecar

  db.redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
