version: "3.7"

services:
  service.api-gateway:
    image: traefik:2.1
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/service.api-gateway/traefik.yaml:/etc/traefik/traefik.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.kiuru.localhost`)
      - traefik.http.routers.traefik.service=api@internal

  client.web:
    build: ./frontend/client.web
    image: kiuru/client.web:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.client-web.rule=Host(`kiuru.localhost`)
      - traefik.http.services.client-web.loadbalancer.server.port=8080

  service.auth:
    build: ./backend/service.auth
    image: kiuru/service.auth:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-auth.rule=Host(`api.kiuru.localhost`) && PathPrefix(`/auth`)
      - traefik.http.routers.service-auth.middlewares=service-auth
      - traefik.http.middlewares.service-auth.replacepathregex.regex=^/auth(.*)
      - traefik.http.middlewares.service-auth.replacepathregex.replacement=/v1/auth$$1
      - traefik.http.services.service-auth.loadbalancer.server.port=8080
    environment:
      PORT: 8081
      GATEWAY_PORT: 8080
      CRDB_HOST: db.cockroach:26257
      CRDB_USER: kiuru_service
      CRDB_DBNAME: kiuru
      REDIS_HOST: db.redis:6379
      JWT_SECRET: my-secret-key
      JWT_ISSUER: kiuru.service.auth
      JWT_TTL: 15m

  service.user:
    build: ./backend/service.user
    image: kiuru/service.user:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-user.rule=Host(`api.kiuru.localhost`) && PathPrefix(`/users`)
      - traefik.http.middlewares.service-user.replacepathregex.regex=^/users(.*)
      - traefik.http.middlewares.service-user.replacepathregex.replacement=/v1/users$$1
      - traefik.http.routers.service-user.middlewares=service-user
      - traefik.http.services.service-user.loadbalancer.server.port=8080
    environment:
      PORT: 8081
      GATEWAY_PORT: 8080
      CRDB_HOST: db.cockroach:26257
      CRDB_USER: kiuru_service
      CRDB_DBNAME: kiuru
      REDIS_HOST: db.redis:6379
      JWT_SECRET: my-secret-key

  db.cockroach:
    image: cockroachdb/cockroach:v19.2.3
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 9000:8080

  db.cockroach.init:
    image: cockroachdb/cockroach:v19.2.3
    entrypoint: /cockroach/init/init-db
    command: db.cockroach:26257
    volumes:
      - ./databases/cockroach/init:/cockroach/init

  db.redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
