#!/bin/sh

exec service \
  --port "$PORT" \
  --gateway-port "$GATEWAY_PORT" \
  --crdb-host "$CRDB_HOST" \
  --crdb-port "${CRDB_PORT:-26257}" \
  --crdb-user "$CRDB_USER" \
  --crdb-dbname "$CRDB_DBNAME" \
  --redis-host "$REDIS_HOST" \
  --redis-port "${REDIS_PORT:-6379}" \
  --jwt-secret "$JWT_SECRET"
