version: 2
jobs:
  client.web:
    docker:
      - image: circleci/node:10.16-stretch
    working_directory: ~/kru-travel/frontend/client.web
    steps:
      - checkout:
          path: ~/kru-travel
      - restore_cache:
          key: client.web-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - save_cache:
          key: client.web-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  service.user:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/kru-travel/backend/service.user
    steps:
      - checkout:
          path: ~/kru-travel
      - run: ~/kru-travel/.circleci/setup/protoc.sh go
      - restore_cache:
          key: service.user-cache-{{ checksum "go.sum" }}
      - run:
          name: install
          command: go mod download
      - run:
          name: lint
          command: |
            if [ -n "$(gofmt -l .)" ]; then
              exit 1
            fi
      - run:
          name: verify proto
          command: |
            make proto
            if [ $(git diff | wc -l) -gt 0 ]; then
              echo "Generated code not up to date with proto schema"
              exit 1
            fi
      - run:
          name: test
          command: make test
      - save_cache:
          key: service.user-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

workflows:
  version: 2
  kru-travel:
    jobs:
      - client.web
      - service.user
