version: 2
jobs:
  client.web:
    docker:
      - image: circleci/node:10.16-stretch
    working_directory: ~/kru.travel/frontend/client.web
    steps:
      - checkout:
          path: ~/kru.travel
      - restore_cache:
          key: client.web-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: client.web-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
workflows:
  version: 2
  kru.travel:
    jobs:
      - client.web
