// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateAuthTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAuthTokenRequest) Reset()         { *m = GenerateAuthTokenRequest{} }
func (m *GenerateAuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAuthTokenRequest) ProtoMessage()    {}
func (*GenerateAuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *GenerateAuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAuthTokenRequest.Unmarshal(m, b)
}
func (m *GenerateAuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAuthTokenRequest.Merge(m, src)
}
func (m *GenerateAuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAuthTokenRequest.Size(m)
}
func (m *GenerateAuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAuthTokenRequest proto.InternalMessageInfo

func (m *GenerateAuthTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GenerateAuthTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GenerateAuthTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAuthTokenResponse) Reset()         { *m = GenerateAuthTokenResponse{} }
func (m *GenerateAuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAuthTokenResponse) ProtoMessage()    {}
func (*GenerateAuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *GenerateAuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAuthTokenResponse.Unmarshal(m, b)
}
func (m *GenerateAuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAuthTokenResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAuthTokenResponse.Merge(m, src)
}
func (m *GenerateAuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAuthTokenResponse.Size(m)
}
func (m *GenerateAuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAuthTokenResponse proto.InternalMessageInfo

func (m *GenerateAuthTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshAuthTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAuthTokenRequest) Reset()         { *m = RefreshAuthTokenRequest{} }
func (m *RefreshAuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshAuthTokenRequest) ProtoMessage()    {}
func (*RefreshAuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RefreshAuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAuthTokenRequest.Unmarshal(m, b)
}
func (m *RefreshAuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshAuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAuthTokenRequest.Merge(m, src)
}
func (m *RefreshAuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshAuthTokenRequest.Size(m)
}
func (m *RefreshAuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAuthTokenRequest proto.InternalMessageInfo

func (m *RefreshAuthTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshAuthTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAuthTokenResponse) Reset()         { *m = RefreshAuthTokenResponse{} }
func (m *RefreshAuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshAuthTokenResponse) ProtoMessage()    {}
func (*RefreshAuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *RefreshAuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAuthTokenResponse.Unmarshal(m, b)
}
func (m *RefreshAuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAuthTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshAuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAuthTokenResponse.Merge(m, src)
}
func (m *RefreshAuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshAuthTokenResponse.Size(m)
}
func (m *RefreshAuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAuthTokenResponse proto.InternalMessageInfo

func (m *RefreshAuthTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RevokeAuthTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeAuthTokenRequest) Reset()         { *m = RevokeAuthTokenRequest{} }
func (m *RevokeAuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeAuthTokenRequest) ProtoMessage()    {}
func (*RevokeAuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *RevokeAuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeAuthTokenRequest.Unmarshal(m, b)
}
func (m *RevokeAuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeAuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *RevokeAuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeAuthTokenRequest.Merge(m, src)
}
func (m *RevokeAuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeAuthTokenRequest.Size(m)
}
func (m *RevokeAuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeAuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeAuthTokenRequest proto.InternalMessageInfo

func (m *RevokeAuthTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RevokeAuthTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeAuthTokenResponse) Reset()         { *m = RevokeAuthTokenResponse{} }
func (m *RevokeAuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeAuthTokenResponse) ProtoMessage()    {}
func (*RevokeAuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *RevokeAuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeAuthTokenResponse.Unmarshal(m, b)
}
func (m *RevokeAuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeAuthTokenResponse.Marshal(b, m, deterministic)
}
func (m *RevokeAuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeAuthTokenResponse.Merge(m, src)
}
func (m *RevokeAuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeAuthTokenResponse.Size(m)
}
func (m *RevokeAuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeAuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeAuthTokenResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenerateAuthTokenRequest)(nil), "auth.GenerateAuthTokenRequest")
	proto.RegisterType((*GenerateAuthTokenResponse)(nil), "auth.GenerateAuthTokenResponse")
	proto.RegisterType((*RefreshAuthTokenRequest)(nil), "auth.RefreshAuthTokenRequest")
	proto.RegisterType((*RefreshAuthTokenResponse)(nil), "auth.RefreshAuthTokenResponse")
	proto.RegisterType((*RevokeAuthTokenRequest)(nil), "auth.RevokeAuthTokenRequest")
	proto.RegisterType((*RevokeAuthTokenResponse)(nil), "auth.RevokeAuthTokenResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0xea, 0xff, 0x47, 0x30, 0x48, 0x7c, 0x18, 0x28, 0xa9, 0x69, 0x4b, 0xf1, 0x0a,
	0x75, 0x11, 0x53, 0xd8, 0x75, 0xc7, 0x8a, 0x7d, 0xe0, 0x02, 0x06, 0x86, 0x26, 0x2a, 0xd8, 0xc1,
	0x76, 0xc2, 0x9e, 0x2b, 0x70, 0x34, 0xae, 0x80, 0x38, 0x07, 0x72, 0x9c, 0x22, 0x91, 0x0f, 0xc4,
	0x2e, 0xe3, 0x37, 0xf3, 0x7e, 0xe3, 0x17, 0x03, 0x88, 0xdc, 0x26, 0x51, 0xa6, 0x95, 0x55, 0xe4,
	0x9f, 0xfb, 0xa6, 0xc3, 0x85, 0x52, 0x8b, 0x47, 0xe4, 0x22, 0x4b, 0xb9, 0x90, 0x52, 0x59, 0x61,
	0x53, 0x25, 0x8d, 0xef, 0x61, 0x31, 0x84, 0x57, 0x28, 0x51, 0x0b, 0x8b, 0x97, 0xb9, 0x4d, 0x6e,
	0xd4, 0x12, 0x65, 0x8c, 0xcf, 0x39, 0x1a, 0x4b, 0x28, 0xac, 0xe7, 0x06, 0xb5, 0x14, 0x4f, 0x18,
	0x06, 0x93, 0xe0, 0x74, 0x23, 0xfe, 0xae, 0x9d, 0x96, 0x09, 0x63, 0x5e, 0x94, 0xbe, 0x0f, 0x7b,
	0x5e, 0x5b, 0xd5, 0x6c, 0x06, 0x83, 0x16, 0x4f, 0x93, 0x29, 0x69, 0x90, 0xec, 0xc3, 0x7f, 0xeb,
	0x0e, 0x2a, 0x47, 0x5f, 0x30, 0x0e, 0x87, 0x31, 0x3e, 0x68, 0x34, 0x49, 0x63, 0x8b, 0xf6, 0x81,
	0x33, 0x08, 0x9b, 0x03, 0xbf, 0x22, 0x22, 0xe8, 0xc7, 0x58, 0xa8, 0x25, 0xfe, 0x91, 0x30, 0x70,
	0x2b, 0xd5, 0xfa, 0x3d, 0xe0, 0xfc, 0xb3, 0x07, 0x9b, 0xee, 0xf4, 0x1a, 0x75, 0x91, 0xde, 0x21,
	0x51, 0xb0, 0xdb, 0xb8, 0x30, 0x19, 0x47, 0xe5, 0xaf, 0xe8, 0x4a, 0x97, 0x1e, 0x77, 0xea, 0x9e,
	0xc2, 0x06, 0xaf, 0xef, 0x1f, 0x6f, 0xbd, 0x3d, 0xb6, 0xc5, 0x8b, 0x19, 0x77, 0xbd, 0xbc, 0x5c,
	0x6c, 0x1e, 0x4c, 0x89, 0x85, 0x9d, 0xfa, 0xed, 0xc9, 0xc8, 0xfb, 0x75, 0xc4, 0x48, 0xc7, 0x5d,
	0x72, 0x45, 0x3b, 0x29, 0x69, 0x47, 0xac, 0xff, 0x93, 0xc6, 0xb5, 0x1f, 0x70, 0xd4, 0x0c, 0xb6,
	0x6b, 0x89, 0x90, 0xe1, 0xca, 0xb5, 0x2d, 0x58, 0x3a, 0xea, 0x50, 0x2b, 0xe4, 0xa4, 0x44, 0x52,
	0x76, 0xd0, 0x40, 0xba, 0xfe, 0x79, 0x30, 0xbd, 0x5d, 0x2b, 0x1f, 0xe9, 0xc5, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0x02, 0x32, 0xd9, 0xd6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GenerateAuthToken(ctx context.Context, in *GenerateAuthTokenRequest, opts ...grpc.CallOption) (*GenerateAuthTokenResponse, error)
	RefreshAuthToken(ctx context.Context, in *RefreshAuthTokenRequest, opts ...grpc.CallOption) (*RefreshAuthTokenResponse, error)
	RevokeAuthToken(ctx context.Context, in *RevokeAuthTokenRequest, opts ...grpc.CallOption) (*RevokeAuthTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GenerateAuthToken(ctx context.Context, in *GenerateAuthTokenRequest, opts ...grpc.CallOption) (*GenerateAuthTokenResponse, error) {
	out := new(GenerateAuthTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/GenerateAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshAuthToken(ctx context.Context, in *RefreshAuthTokenRequest, opts ...grpc.CallOption) (*RefreshAuthTokenResponse, error) {
	out := new(RefreshAuthTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/RefreshAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeAuthToken(ctx context.Context, in *RevokeAuthTokenRequest, opts ...grpc.CallOption) (*RevokeAuthTokenResponse, error) {
	out := new(RevokeAuthTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/RevokeAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GenerateAuthToken(context.Context, *GenerateAuthTokenRequest) (*GenerateAuthTokenResponse, error)
	RefreshAuthToken(context.Context, *RefreshAuthTokenRequest) (*RefreshAuthTokenResponse, error)
	RevokeAuthToken(context.Context, *RevokeAuthTokenRequest) (*RevokeAuthTokenResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GenerateAuthToken(ctx context.Context, req *GenerateAuthTokenRequest) (*GenerateAuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAuthToken not implemented")
}
func (*UnimplementedAuthServiceServer) RefreshAuthToken(ctx context.Context, req *RefreshAuthTokenRequest) (*RefreshAuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAuthToken not implemented")
}
func (*UnimplementedAuthServiceServer) RevokeAuthToken(ctx context.Context, req *RevokeAuthTokenRequest) (*RevokeAuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAuthToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GenerateAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/GenerateAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateAuthToken(ctx, req.(*GenerateAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/RefreshAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshAuthToken(ctx, req.(*RefreshAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/RevokeAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeAuthToken(ctx, req.(*RevokeAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAuthToken",
			Handler:    _AuthService_GenerateAuthToken_Handler,
		},
		{
			MethodName: "RefreshAuthToken",
			Handler:    _AuthService_RefreshAuthToken_Handler,
		},
		{
			MethodName: "RevokeAuthToken",
			Handler:    _AuthService_RevokeAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
