ALTER RANGE default CONFIGURE ZONE USING num_replicas = 1;

CREATE DATABASE IF NOT EXISTS kiuru;

CREATE TABLE IF NOT EXISTS kiuru.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  username STRING UNIQUE,
  password STRING,
  name STRING,
  email STRING UNIQUE
);

CREATE USER IF NOT EXISTS kiuru_admin;
GRANT ALL ON DATABASE kiuru TO kiuru_admin;
CREATE USER IF NOT EXISTS kiuru_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE kiuru.* TO kiuru_service;
