#!/usr/bin/env bash

echo "> Connecting to cluster"
until /cockroach/cockroach init --insecure --host=$1 2>&1 >/dev/null | grep -q "cluster has already been initialized"; do sleep 1; done

echo "> Initializing database"
/cockroach/cockroach sql --insecure --host=$1 < /cockroach/init/init.sql

echo "> Seeding database"
/cockroach/cockroach sql --insecure --host=$1 < /cockroach/init/seed.sql
