#!/bin/sh

exec service \
  --port "$PORT" \
  --gateway-port "$GATEWAY_PORT" \
  --crdb-host "$CRDB_HOST" \
  --crdb-port "${CRDB_PORT:-26257}" \
  --crdb-user "$CRDB_USER" \
  --crdb-dbname "$CRDB_NAME" \
  --redis-host "$REDIS_HOST" \
  --redis-port "${REDIS_PORT:-6379}" \
  --token-secret "$TOKEN_SECRET" \
  --token-issuer "$TOKEN_ISSUER" \
  --token-ttl "${TOKEN_TTL:-15m}"
