#!/bin/sh

exec ./service \
  --port "${PORT:-8080}" \
  --gateway-port "${GATEWAY_PORT:-8081}" \
  --crdb-host "${CRDB_HOST:-127.0.0.1}" \
  --crdb-port "${CRDB_PORT:-26257}" \
  --crdb-user "${CRDB_USER:-kru_service}" \
  --crdb-dbname "${CRDB_NAME:-kru}" \
  --redis-host "${REDIS_HOST:-127.0.0.1}" \
  --redis-port "${REDIS_PORT:-6379}" \
  --token-secret "${TOKEN_SECRET:-my-secret-key}" \
  --token-issuer "${TOKEN_ISSUER:-kru.service.auth}" \
  --token-ttl "${TOKEN_TTL:-15m}"
